import { useState } from 'react'
import { Trash2, CheckSquare, Square, Filter, SortDesc, Sparkles, ChevronLeft, ChevronRight } from 'lucide-react'
import { Modal } from './ui/Modal'
import { Button } from './ui/button'
import type { Annotation, Label } from '../types/annotations'

interface SidebarProps {
  annotations: Annotation[]
  labels: Label[]
  selectedAnnotation: string | null
  selectedLabelId: string | null
  onSelectAnnotation: (id: string) => void
  onSelectLabel: (id: string) => void
  onDeleteAnnotation: (id: string) => void
  onBulkDeleteAnnotations: (ids: string[]) => void
}

type FilterMode = 'all' | 'manual' | 'auto'
type SortMode = 'newest' | 'confidence-high' | 'confidence-low'

export default function Sidebar({
  annotations,
  labels,
  selectedAnnotation,
  selectedLabelId,
  onSelectAnnotation,
  onSelectLabel,
  onDeleteAnnotation,
  onBulkDeleteAnnotations,
}: SidebarProps) {
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [filterMode, setFilterMode] = useState<FilterMode>('all')
  const [sortMode, setSortMode] = useState<SortMode>('newest')
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const [showThresholdModal, setShowThresholdModal] = useState(false)
  const [confidenceThreshold, setConfidenceThreshold] = useState(0.5)
  const [isCollapsed, setIsCollapsed] = useState(false)

  const getLabel = (labelId: string) => {
    return labels.find(l => l.id === labelId)
  }

  const selectedLabel = labels.find(l => l.id === selectedLabelId)

  // Filter annotations
  const filteredAnnotations = annotations.filter(ann => {
    if (filterMode === 'manual') return !ann.isAutoGenerated
    if (filterMode === 'auto') return ann.isAutoGenerated
    return true
  })

  // Sort annotations
  const sortedAnnotations = [...filteredAnnotations].sort((a, b) => {
    if (sortMode === 'newest') {
      return b.createdAt - a.createdAt
    }
    if (sortMode === 'confidence-high') {
      const aConf = a.confidence ?? -1
      const bConf = b.confidence ?? -1
      return bConf - aConf
    }
    if (sortMode === 'confidence-low') {
      const aConf = a.confidence ?? 999
      const bConf = b.confidence ?? 999
      return aConf - bConf
    }
    return 0
  })

  const toggleSelection = (id: string) => {
    const newSelection = new Set(selectedIds)
    if (newSelection.has(id)) {
      newSelection.delete(id)
    } else {
      newSelection.add(id)
    }
    setSelectedIds(newSelection)
  }

  const toggleSelectAll = () => {
    if (selectedIds.size === sortedAnnotations.length) {
      setSelectedIds(new Set())
    } else {
      setSelectedIds(new Set(sortedAnnotations.map(a => a.id)))
    }
  }

  const handleDeleteSelected = () => {
    if (selectedIds.size > 0) {
      onBulkDeleteAnnotations(Array.from(selectedIds))
      setSelectedIds(new Set())
      setShowDeleteConfirm(false)
    }
  }

  const handleDeleteAll = () => {
    if (annotations.length > 0) {
      onBulkDeleteAnnotations(annotations.map(a => a.id))
      setSelectedIds(new Set())
      setShowDeleteConfirm(false)
    }
  }

  const handleRemoveLowConfidence = () => {
    const lowConfidenceIds = annotations
      .filter(a => a.isAutoGenerated && (a.confidence ?? 0) < confidenceThreshold)
      .map(a => a.id)

    if (lowConfidenceIds.length > 0) {
      onBulkDeleteAnnotations(lowConfidenceIds)
      setShowThresholdModal(false)
    }
  }

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 0.8) return 'text-green-400 bg-green-900/30'
    if (confidence >= 0.6) return 'text-yellow-400 bg-yellow-900/30'
    return 'text-red-400 bg-red-900/30'
  }

  const autoAnnotationsCount = annotations.filter(a => a.isAutoGenerated).length
  const lowConfidenceCount = annotations.filter(a => a.isAutoGenerated && (a.confidence ?? 0) < confidenceThreshold).length

  return (
    <div className={`${isCollapsed ? 'w-12' : 'w-80'} bg-gray-800 border-l border-gray-700 flex flex-col transition-all duration-300`}>
      {/* Collapse/Expand Button */}
      <div className="px-2 py-2 border-b border-gray-700 flex justify-end">
        <button
          onClick={() => setIsCollapsed(!isCollapsed)}
          className="p-2 rounded hover:bg-gray-700 transition-colors text-gray-400 hover:text-white"
          title={isCollapsed ? 'Expand sidebar' : 'Collapse sidebar'}
        >
          {isCollapsed ? <ChevronLeft className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
        </button>
      </div>

      {!isCollapsed && (
        <>
      {/* Header */}
      <div className="px-4 py-3 border-b border-gray-700">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold text-white">Annotations</h2>
            <p className="text-sm text-gray-400">
              {annotations.length} total
              {autoAnnotationsCount > 0 && ` • ${autoAnnotationsCount} auto`}
            </p>
          </div>
          {sortedAnnotations.length > 0 && (
            <button
              onClick={toggleSelectAll}
              className="p-1 rounded hover:bg-gray-700 transition-colors text-gray-400 hover:text-white"
              title={selectedIds.size === sortedAnnotations.length ? 'Deselect all' : 'Select all'}
            >
              {selectedIds.size === sortedAnnotations.length ? (
                <CheckSquare className="w-5 h-5" />
              ) : (
                <Square className="w-5 h-5" />
              )}
            </button>
          )}
        </div>

        {/* Bulk Actions */}
        {selectedIds.size > 0 && (
          <div className="mt-3 flex gap-2">
            <button
              onClick={() => setShowDeleteConfirm(true)}
              className="flex-1 px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white text-sm rounded transition-colors flex items-center justify-center gap-1.5"
            >
              <Trash2 className="w-4 h-4" />
              Delete {selectedIds.size}
            </button>
          </div>
        )}
      </div>

      {/* Label Selector */}
      <div className="px-4 py-3 border-b border-gray-700 bg-gray-750">
        <label className="block text-sm font-medium text-gray-300 mb-2">
          Selected Label
        </label>
        <select
          value={selectedLabelId || ''}
          onChange={(e) => onSelectLabel(e.target.value)}
          className="w-full px-3 py-2 bg-gray-700 text-white rounded border border-gray-600 focus:border-orange-500 focus:outline-none text-sm"
        >
          {labels.length === 0 ? (
            <option value="">No labels available</option>
          ) : (
            labels.map(label => (
              <option key={label.id} value={label.id}>
                {label.name}
              </option>
            ))
          )}
        </select>
        {selectedLabel && (
          <div className="mt-2 flex items-center gap-2 text-sm text-gray-400">
            <div
              className="w-4 h-4 rounded"
              style={{ backgroundColor: selectedLabel.color }}
            />
            <span>New annotations will use this label</span>
          </div>
        )}
      </div>

      {/* Filter and Sort Controls */}
      {annotations.length > 0 && (
        <div className="px-4 py-3 border-b border-gray-700 space-y-3">
          {/* Filter */}
          <div>
            <label className="flex items-center gap-2 text-sm font-medium text-gray-300 mb-2">
              <Filter className="w-4 h-4" />
              Filter
            </label>
            <div className="flex gap-1">
              <button
                onClick={() => setFilterMode('all')}
                className={`flex-1 px-2 py-1 text-xs rounded transition-colors ${
                  filterMode === 'all'
                    ? 'bg-purple-600 text-white'
                    : 'bg-gray-700 text-gray-400 hover:bg-gray-650'
                }`}
              >
                All
              </button>
              <button
                onClick={() => setFilterMode('manual')}
                className={`flex-1 px-2 py-1 text-xs rounded transition-colors ${
                  filterMode === 'manual'
                    ? 'bg-purple-600 text-white'
                    : 'bg-gray-700 text-gray-400 hover:bg-gray-650'
                }`}
              >
                Manual
              </button>
              <button
                onClick={() => setFilterMode('auto')}
                className={`flex-1 px-2 py-1 text-xs rounded transition-colors ${
                  filterMode === 'auto'
                    ? 'bg-purple-600 text-white'
                    : 'bg-gray-700 text-gray-400 hover:bg-gray-650'
                }`}
              >
                Auto
              </button>
            </div>
          </div>

          {/* Sort */}
          <div>
            <label className="flex items-center gap-2 text-sm font-medium text-gray-300 mb-2">
              <SortDesc className="w-4 h-4" />
              Sort
            </label>
            <select
              value={sortMode}
              onChange={(e) => setSortMode(e.target.value as SortMode)}
              className="w-full px-2 py-1.5 bg-gray-700 text-white rounded border border-gray-600 focus:border-purple-500 focus:outline-none text-xs"
            >
              <option value="newest">Newest First</option>
              <option value="confidence-high">Confidence (High → Low)</option>
              <option value="confidence-low">Confidence (Low → High)</option>
            </select>
          </div>

          {/* Remove Low Confidence */}
          {autoAnnotationsCount > 0 && (
            <button
              onClick={() => setShowThresholdModal(true)}
              className="w-full px-3 py-1.5 bg-orange-600 hover:bg-orange-700 text-white text-xs rounded transition-colors flex items-center justify-center gap-1.5"
            >
              <Sparkles className="w-3 h-3" />
              Remove Low Confidence
            </button>
          )}
        </div>
      )}

      {/* Annotations List */}
      <div className="flex-1 overflow-y-auto p-4 space-y-2">
        {sortedAnnotations.length === 0 ? (
          <p className="text-gray-400 text-sm text-center mt-8">
            {annotations.length === 0
              ? 'No annotations yet. Start drawing on the canvas.'
              : 'No annotations match the current filter.'}
          </p>
        ) : (
          sortedAnnotations.map((annotation, index) => {
            const label = getLabel(annotation.labelId)
            const labelName = label?.name || 'Unknown'
            const labelColor = label?.color || '#6b7280'
            const isSelected = selectedIds.has(annotation.id)

            return (
              <div
                key={annotation.id}
                className={`
                  p-3 rounded-lg border transition-colors
                  ${selectedAnnotation === annotation.id
                    ? 'bg-orange-900/30 border-orange-600'
                    : isSelected
                    ? 'bg-purple-900/30 border-purple-600'
                    : 'bg-gray-700 border-gray-600 hover:bg-gray-650'
                  }
                `}
              >
                <div className="flex items-start gap-2">
                  {/* Checkbox */}
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      toggleSelection(annotation.id)
                    }}
                    className="mt-0.5 text-gray-400 hover:text-white transition-colors"
                  >
                    {isSelected ? (
                      <CheckSquare className="w-4 h-4 text-purple-500" />
                    ) : (
                      <Square className="w-4 h-4" />
                    )}
                  </button>

                  {/* Content */}
                  <div
                    onClick={() => onSelectAnnotation(annotation.id)}
                    className="flex-1 cursor-pointer"
                  >
                    <div className="flex items-center gap-2 flex-wrap">
                      <div
                        className="w-3 h-3 rounded"
                        style={{ backgroundColor: labelColor }}
                      />
                      <span className="text-white font-medium text-sm">
                        {labelName} #{index + 1}
                      </span>
                      {annotation.isAutoGenerated && annotation.confidence !== undefined && (
                        <span className={`text-xs px-1.5 py-0.5 rounded ${getConfidenceColor(annotation.confidence)}`}>
                          {(annotation.confidence * 100).toFixed(0)}%
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-2 mt-1">
                      <p className="text-xs text-gray-400 capitalize">
                        {annotation.type}
                      </p>
                      {annotation.isAutoGenerated && (
                        <span className="text-xs text-purple-400 flex items-center gap-1">
                          <Sparkles className="w-3 h-3" />
                          Auto
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Delete Button */}
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      onDeleteAnnotation(annotation.id)
                    }}
                    className="p-1 rounded hover:bg-red-600 transition-colors text-gray-400 hover:text-white"
                    title="Delete annotation"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            )
          })
        )}
      </div>

      {/* Delete All Button */}
      {annotations.length > 0 && (
        <div className="px-4 py-3 border-t border-gray-700">
          <button
            onClick={() => setShowDeleteConfirm(true)}
            className="w-full px-3 py-2 bg-red-600/20 hover:bg-red-600/30 text-red-400 text-sm rounded transition-colors flex items-center justify-center gap-1.5 border border-red-600/30"
          >
            <Trash2 className="w-4 h-4" />
            Delete All Annotations
          </button>
        </div>
      )}

      {/* Footer Info */}
      <div className="px-4 py-3 border-t border-gray-700 bg-gray-850">
        <p className="text-xs text-gray-400">
          Click annotations to select • Drag to move • Use handles to resize
        </p>
      </div>
      </>
      )}

      {/* Delete Confirmation Modal */}
      <Modal
        isOpen={showDeleteConfirm}
        onClose={() => setShowDeleteConfirm(false)}
        title="Confirm Deletion"
        maxWidth="md"
      >
        <div className="space-y-4">
          <p className="text-gray-300">
            {selectedIds.size > 0
              ? `Are you sure you want to delete ${selectedIds.size} selected annotation${selectedIds.size > 1 ? 's' : ''}?`
              : `Are you sure you want to delete all ${annotations.length} annotations?`}
          </p>
          <p className="text-sm text-gray-400">
            This action cannot be undone.
          </p>
          <div className="flex justify-end space-x-3 pt-4 border-t border-gray-700">
            <Button variant="outline" onClick={() => setShowDeleteConfirm(false)}>
              Cancel
            </Button>
            <Button
              onClick={selectedIds.size > 0 ? handleDeleteSelected : handleDeleteAll}
              className="bg-red-600 hover:bg-red-700"
            >
              Delete
            </Button>
          </div>
        </div>
      </Modal>

      {/* Threshold Modal */}
      <Modal
        isOpen={showThresholdModal}
        onClose={() => setShowThresholdModal(false)}
        title="Remove Low Confidence Annotations"
        maxWidth="md"
      >
        <div className="space-y-4">
          <p className="text-gray-300">
            Remove auto-generated annotations below a confidence threshold.
          </p>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Confidence Threshold: {(confidenceThreshold * 100).toFixed(0)}%
            </label>
            <input
              type="range"
              min="0"
              max="1"
              step="0.05"
              value={confidenceThreshold}
              onChange={(e) => setConfidenceThreshold(parseFloat(e.target.value))}
              className="w-full h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer accent-orange-600"
            />
            <div className="flex justify-between text-xs text-gray-400 mt-1">
              <span>0%</span>
              <span>50%</span>
              <span>100%</span>
            </div>
          </div>

          <div className="p-3 bg-gray-700 rounded-lg">
            <p className="text-sm text-gray-300">
              <span className="font-medium text-orange-400">{lowConfidenceCount}</span> annotation{lowConfidenceCount !== 1 ? 's' : ''} will be removed
            </p>
          </div>

          <div className="flex justify-end space-x-3 pt-4 border-t border-gray-700">
            <Button variant="outline" onClick={() => setShowThresholdModal(false)}>
              Cancel
            </Button>
            <Button
              onClick={handleRemoveLowConfidence}
              disabled={lowConfidenceCount === 0}
              className="bg-orange-600 hover:bg-orange-700 disabled:bg-gray-700 disabled:opacity-50"
            >
              Remove {lowConfidenceCount}
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  )
}
