import { useState } from 'react'
import { Trash2, Eye, EyeOff, ChevronDown, ChevronRight, Square as SquareIcon, Shapes, Circle, Filter, SortDesc, Sparkles, ChevronLeft } from 'lucide-react'
import { Modal } from './ui/Modal'
import type { Annotation, Label } from '../types/annotations'

type FilterMode = 'all' | 'manual' | 'auto'
type SortMode = 'newest' | 'confidence-high' | 'confidence-low'

interface SidebarProps {
  annotations: Annotation[]
  labels: Label[]
  selectedAnnotation: string | null
  selectedLabelId: string | null
  onSelectAnnotation: (id: string) => void
  onSelectLabel: (id: string) => void
  onDeleteAnnotation: (id: string) => void
  onBulkDeleteAnnotations: (ids: string[]) => void
  onBulkChangeLabel: (annotationIds: string[], newLabelId: string) => void
  onToggleAnnotationVisibility: (annotationId: string) => void
  onBulkToggleVisibility: (annotationIds: string[]) => void
  isCollapsed: boolean
  onToggleCollapse: () => void
}

export default function Sidebar({
  annotations,
  labels,
  selectedAnnotation,
  selectedLabelId,
  onSelectAnnotation,
  onSelectLabel,
  onDeleteAnnotation,
  onBulkDeleteAnnotations,
  onBulkChangeLabel,
  onToggleAnnotationVisibility,
  onBulkToggleVisibility,
  isCollapsed,
  onToggleCollapse,
}: SidebarProps) {
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [expandedLabels, setExpandedLabels] = useState<Record<string, boolean>>(() => {
    // Default all labels to expanded
    const initial: Record<string, boolean> = {}
    labels.forEach(label => {
      initial[label.id] = true
    })
    return initial
  })
  const [bulkChangeLabelId, setBulkChangeLabelId] = useState<string>('')
  const [filterMode, setFilterMode] = useState<FilterMode>('all')
  const [sortMode, setSortMode] = useState<SortMode>('newest')
  const [showDeleteAllConfirm, setShowDeleteAllConfirm] = useState(false)
  const [showThresholdModal, setShowThresholdModal] = useState(false)
  const [confidenceThreshold, setConfidenceThreshold] = useState(0.5)

  const getLabel = (labelId: string) => {
    return labels.find(l => l.id === labelId)
  }

  // Filter annotations
  const filteredAnnotations = annotations.filter(ann => {
    if (filterMode === 'manual') return !ann.isAutoGenerated
    if (filterMode === 'auto') return ann.isAutoGenerated
    return true
  })

  // Sort annotations
  const sortedAnnotations = [...filteredAnnotations].sort((a, b) => {
    if (sortMode === 'newest') {
      return b.createdAt - a.createdAt
    }
    if (sortMode === 'confidence-high') {
      const aConf = a.confidence ?? -1
      const bConf = b.confidence ?? -1
      return bConf - aConf
    }
    if (sortMode === 'confidence-low') {
      const aConf = a.confidence ?? 999
      const bConf = b.confidence ?? 999
      return aConf - bConf
    }
    return 0
  })

  // Group annotations by label
  const annotationsByLabel: Record<string, Annotation[]> = {}
  sortedAnnotations.forEach(ann => {
    if (!annotationsByLabel[ann.labelId]) {
      annotationsByLabel[ann.labelId] = []
    }
    annotationsByLabel[ann.labelId].push(ann)
  })

  // Count auto annotations and low confidence
  const autoAnnotationsCount = annotations.filter(a => a.isAutoGenerated).length
  const lowConfidenceCount = annotations.filter(a => a.isAutoGenerated && (a.confidence ?? 0) < confidenceThreshold).length

  // Toggle label expansion
  const toggleLabelExpanded = (labelId: string) => {
    setExpandedLabels(prev => ({
      ...prev,
      [labelId]: !prev[labelId],
    }))
  }

  // Toggle individual annotation selection
  const toggleSelection = (id: string) => {
    const newSelection = new Set(selectedIds)
    if (newSelection.has(id)) {
      newSelection.delete(id)
    } else {
      newSelection.add(id)
    }
    setSelectedIds(newSelection)
  }

  // Toggle all annotations under a label
  const toggleSelectAllForLabel = (labelId: string) => {
    const labelAnnotations = annotationsByLabel[labelId] || []
    const labelAnnotationIds = labelAnnotations.map(a => a.id)
    const allSelected = labelAnnotationIds.every(id => selectedIds.has(id))

    const newSelection = new Set(selectedIds)
    if (allSelected) {
      // Deselect all
      labelAnnotationIds.forEach(id => newSelection.delete(id))
    } else {
      // Select all
      labelAnnotationIds.forEach(id => newSelection.add(id))
    }
    setSelectedIds(newSelection)
  }

  // Handle bulk delete
  const handleBulkDelete = () => {
    if (selectedIds.size > 0) {
      onBulkDeleteAnnotations(Array.from(selectedIds))
      setSelectedIds(new Set())
    }
  }

  // Handle bulk change label
  const handleBulkLabelChange = () => {
    if (selectedIds.size > 0 && bulkChangeLabelId) {
      onBulkChangeLabel(Array.from(selectedIds), bulkChangeLabelId)
      setSelectedIds(new Set())
      setBulkChangeLabelId('')
    }
  }

  // Handle delete all annotations
  const handleDeleteAll = () => {
    if (annotations.length > 0) {
      onBulkDeleteAnnotations(annotations.map(a => a.id))
      setSelectedIds(new Set())
      setShowDeleteAllConfirm(false)
    }
  }

  // Handle remove low confidence
  const handleRemoveLowConfidence = () => {
    const lowConfidenceIds = annotations
      .filter(a => a.isAutoGenerated && (a.confidence ?? 0) < confidenceThreshold)
      .map(a => a.id)

    if (lowConfidenceIds.length > 0) {
      onBulkDeleteAnnotations(lowConfidenceIds)
      setShowThresholdModal(false)
    }
  }

  // Toggle visibility for all annotations under a label
  const toggleLabelVisibility = (labelId: string) => {
    const labelAnnotations = annotationsByLabel[labelId] || []
    const annotationIds = labelAnnotations.map(ann => ann.id)

    if (annotationIds.length > 0) {
      onBulkToggleVisibility(annotationIds)
    }
  }

  // Get confidence color
  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 0.8) return 'text-green-400'
    if (confidence >= 0.6) return 'text-yellow-400'
    return 'text-red-400'
  }

  // Get icon for annotation type
  const getAnnotationIcon = (type: string) => {
    switch (type) {
      case 'rectangle':
        return <SquareIcon className="w-4 h-4" />
      case 'polygon':
        return <Shapes className="w-4 h-4" />
      case 'point':
        return <Circle className="w-4 h-4" />
      default:
        return <Shapes className="w-4 h-4" />
    }
  }

  // Collapsed view - thin icon bar
  if (isCollapsed) {
    return (
      <div className="w-12 bg-gray-800 border-l border-gray-700 flex flex-col items-center py-3 gap-3 transition-all duration-300">
        {/* Expand Button */}
        <button
          onClick={onToggleCollapse}
          className="p-2 hover:bg-gray-700 rounded transition-colors text-gray-400 hover:text-white"
          title="Expand Sidebar (Ctrl+B)"
        >
          <ChevronLeft className="w-5 h-5" />
        </button>

        {/* Annotations Icon with Count Badge */}
        <div className="relative">
          <Shapes className="w-5 h-5 text-gray-400" />
          {annotations.length > 0 && (
            <div className="absolute -top-1 -right-1 w-4 h-4 bg-orange-500 text-white text-[10px] rounded-full flex items-center justify-center font-medium">
              {annotations.length > 9 ? '9+' : annotations.length}
            </div>
          )}
        </div>

        {/* Label Groups Count */}
        <div className="text-xs text-gray-400 font-medium">
          {labels.length}
        </div>
      </div>
    )
  }

  // Expanded view - full sidebar
  return (
    <div className="w-80 bg-gray-800 border-l border-gray-700 flex flex-col transition-all duration-300">
      {/* Header */}
      <div className="px-4 py-3 border-b border-gray-700">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold text-white flex items-center gap-2">
            <Shapes className="w-5 h-5" />
            Annotations
          </h2>
          <div className="flex items-center gap-2">
            <div className="text-sm text-gray-400">
              {annotations.length} total
              {autoAnnotationsCount > 0 && ` • ${autoAnnotationsCount} auto`}
            </div>
            <button
              onClick={onToggleCollapse}
              className="p-1 hover:bg-gray-700 rounded transition-colors text-gray-400 hover:text-white"
              title="Collapse Sidebar (Ctrl+B)"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* Filter and Sort Controls */}
      {annotations.length > 0 && (
        <div className="px-4 py-3 border-b border-gray-700 space-y-3">
          {/* Filter */}
          <div>
            <label className="flex items-center gap-2 text-sm font-medium text-gray-300 mb-2">
              <Filter className="w-4 h-4" />
              Filter
            </label>
            <div className="flex gap-1">
              <button
                onClick={() => setFilterMode('all')}
                className={`flex-1 px-2 py-1 text-xs rounded transition-colors ${
                  filterMode === 'all'
                    ? 'bg-purple-600 text-white'
                    : 'bg-gray-700 text-gray-400 hover:bg-gray-650'
                }`}
                title="Show all annotations"
              >
                All
              </button>
              <button
                onClick={() => setFilterMode('manual')}
                className={`flex-1 px-2 py-1 text-xs rounded transition-colors ${
                  filterMode === 'manual'
                    ? 'bg-purple-600 text-white'
                    : 'bg-gray-700 text-gray-400 hover:bg-gray-650'
                }`}
                title="Show only manual annotations"
              >
                Manual
              </button>
              <button
                onClick={() => setFilterMode('auto')}
                className={`flex-1 px-2 py-1 text-xs rounded transition-colors flex items-center justify-center gap-1 ${
                  filterMode === 'auto'
                    ? 'bg-purple-600 text-white'
                    : 'bg-gray-700 text-gray-400 hover:bg-gray-650'
                }`}
                title="Show only AI-generated annotations"
              >
                <Sparkles className="w-3 h-3" />
                Auto
              </button>
            </div>
          </div>

          {/* Sort */}
          <div>
            <label className="flex items-center gap-2 text-sm font-medium text-gray-300 mb-2">
              <SortDesc className="w-4 h-4" />
              Sort
            </label>
            <select
              value={sortMode}
              onChange={(e) => setSortMode(e.target.value as SortMode)}
              className="w-full px-3 py-1.5 bg-gray-700 text-white text-xs rounded border border-gray-600 focus:border-orange-500 focus:outline-none"
              title="Sort annotations by different criteria"
            >
              <option value="newest">Newest First</option>
              <option value="confidence-high">Confidence: High → Low</option>
              <option value="confidence-low">Confidence: Low → High</option>
            </select>
          </div>

          {/* Low Confidence & Delete All */}
          <div className="flex gap-2">
            {autoAnnotationsCount > 0 && (
              <button
                onClick={() => setShowThresholdModal(true)}
                className="flex-1 px-3 py-1.5 bg-gray-700 hover:bg-gray-600 text-white text-xs rounded transition-colors flex items-center justify-center gap-1.5"
                title="Remove AI annotations below confidence threshold"
              >
                <Sparkles className="w-3 h-3" />
                Remove Low ({lowConfidenceCount})
              </button>
            )}
            <button
              onClick={() => setShowDeleteAllConfirm(true)}
              className="flex-1 px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white text-xs rounded transition-colors flex items-center justify-center gap-1.5"
              title="Delete all annotations for this image"
            >
              <Trash2 className="w-3 h-3" />
              Delete All
            </button>
          </div>
        </div>
      )}

      {/* Bulk Actions Panel */}
      {selectedIds.size > 0 && (
        <div className="px-4 py-3 bg-gray-750 border-b border-gray-700 space-y-2">
          <div className="text-sm text-gray-300 font-medium">
            {selectedIds.size} selected
          </div>

          {/* Change Label */}
          <div className="flex gap-2">
            <select
              value={bulkChangeLabelId}
              onChange={(e) => setBulkChangeLabelId(e.target.value)}
              className="flex-1 px-3 py-1.5 bg-gray-700 text-white text-sm rounded border border-gray-600 focus:border-orange-500 focus:outline-none"
              title="Select new label for selected annotations"
            >
              <option value="">Change label...</option>
              {labels.map(label => (
                <option key={label.id} value={label.id}>
                  {label.name}
                </option>
              ))}
            </select>
            <button
              onClick={handleBulkLabelChange}
              disabled={!bulkChangeLabelId}
              className="px-3 py-1.5 bg-orange-600 hover:bg-orange-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white text-sm rounded transition-colors"
              title="Apply label change to selected annotations"
            >
              Apply
            </button>
          </div>

          {/* Bulk Delete */}
          <button
            onClick={handleBulkDelete}
            className="w-full px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white text-sm rounded transition-colors flex items-center justify-center gap-2"
            title="Delete all selected annotations (Del)"
          >
            <Trash2 className="w-4 h-4" />
            Delete {selectedIds.size}
          </button>

          {/* Clear Selection */}
          <button
            onClick={() => setSelectedIds(new Set())}
            className="w-full px-3 py-1.5 bg-gray-700 hover:bg-gray-600 text-white text-sm rounded transition-colors"
            title="Deselect all annotations"
          >
            Clear Selection
          </button>
        </div>
      )}

      {/* Annotations grouped by label */}
      <div className="flex-1 overflow-y-auto">
        {labels.length === 0 ? (
          <div className="p-8 text-center text-gray-400">
            <p className="mb-2">No labels available</p>
            <p className="text-sm">Create labels to start annotating</p>
          </div>
        ) : (
          <div className="space-y-0">
            {labels.map(label => {
              const labelAnnotations = annotationsByLabel[label.id] || []
              const isExpanded = expandedLabels[label.id] ?? true
              const allSelected = labelAnnotations.length > 0 && labelAnnotations.every(a => selectedIds.has(a.id))
              const someSelected = labelAnnotations.some(a => selectedIds.has(a.id)) && !allSelected

              // Check visibility state - all visible, all hidden, or mixed
              const allVisible = labelAnnotations.length > 0 && labelAnnotations.every(a => a.isVisible ?? true)
              const allHidden = labelAnnotations.length > 0 && labelAnnotations.every(a => !(a.isVisible ?? true))

              return (
                <div key={label.id} className="border-b border-gray-700">
                  {/* Label Header */}
                  <div className={`px-3 py-2 transition-colors flex items-center gap-2 ${
                    selectedLabelId === label.id
                      ? 'bg-orange-500/20 border-l-4 border-orange-500'
                      : 'bg-gray-750 hover:bg-gray-700/50'
                  }`}>
                    {/* Active Label Indicator (Radio Button) */}
                    {selectedLabelId === label.id && (
                      <div
                        className="w-3 h-3 rounded-full bg-orange-500 flex-shrink-0"
                        title="Active label for drawing"
                      />
                    )}
                    {selectedLabelId !== label.id && (
                      <div
                        className="w-3 h-3 rounded-full border-2 border-gray-500 flex-shrink-0"
                        title="Click label name to set as active"
                      />
                    )}

                    {/* Select All Checkbox */}
                    {labelAnnotations.length > 0 && (
                      <button
                        onClick={() => toggleSelectAllForLabel(label.id)}
                        className="p-1 hover:bg-gray-600 rounded transition-colors"
                        title={allSelected ? 'Deselect all in this label' : 'Select all in this label'}
                      >
                        <div
                          className={`w-4 h-4 border-2 rounded flex items-center justify-center ${
                            allSelected
                              ? 'bg-orange-500 border-orange-500'
                              : someSelected
                              ? 'bg-orange-500/50 border-orange-500'
                              : 'border-gray-500'
                          }`}
                        >
                          {(allSelected || someSelected) && (
                            <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                            </svg>
                          )}
                        </div>
                      </button>
                    )}

                    {/* Expand/Collapse */}
                    <button
                      onClick={() => toggleLabelExpanded(label.id)}
                      className="p-1 hover:bg-gray-600 rounded transition-colors text-gray-400"
                      title={isExpanded ? 'Collapse label group' : 'Expand label group'}
                    >
                      {isExpanded ? (
                        <ChevronDown className="w-4 h-4" />
                      ) : (
                        <ChevronRight className="w-4 h-4" />
                      )}
                    </button>

                    {/* Color Swatch */}
                    <div
                      className="w-4 h-4 rounded flex-shrink-0"
                      style={{ backgroundColor: label.color }}
                    />

                    {/* Label Name */}
                    <button
                      onClick={() => toggleLabelExpanded(label.id)}
                      className="flex-1 text-left text-sm font-medium text-white truncate"
                      title="Expand/collapse label group"
                    >
                      {label.name}
                    </button>

                    {/* Count Badge */}
                    <div className="px-2 py-0.5 bg-orange-500 text-white text-xs rounded-full font-medium">
                      {labelAnnotations.length}
                    </div>

                    {/* Eye Icon - toggle all annotations for this label */}
                    <button
                      onClick={() => toggleLabelVisibility(label.id)}
                      className="p-1 hover:bg-gray-600 rounded transition-colors text-gray-400 hover:text-white"
                      title={allHidden ? "Show all annotations in this label" : "Hide all annotations in this label"}
                    >
                      {allHidden ? (
                        <EyeOff className="w-4 h-4" />
                      ) : (
                        <Eye className="w-4 h-4" />
                      )}
                    </button>
                  </div>

                  {/* Annotation List */}
                  {isExpanded && (
                    <div className="bg-gray-800">
                      {labelAnnotations.length === 0 ? (
                        <div className="px-4 py-3 text-sm text-gray-500 text-center">
                          No annotations
                        </div>
                      ) : (
                        labelAnnotations.map((ann, index) => {
                          const isSelected = selectedIds.has(ann.id)
                          const isActiveAnnotation = selectedAnnotation === ann.id
                          const isVisible = ann.isVisible ?? true

                          return (
                            <div
                              key={ann.id}
                              className={`px-3 py-2 flex items-center gap-2 hover:bg-gray-700/30 transition-colors ${
                                isActiveAnnotation ? 'bg-orange-500/20 border-l-2 border-orange-500' : ''
                              }`}
                            >
                              {/* Selection Checkbox */}
                              <button
                                onClick={() => toggleSelection(ann.id)}
                                className="p-1 hover:bg-gray-600 rounded transition-colors"
                                title={isSelected ? 'Deselect annotation' : 'Select annotation'}
                              >
                                <div
                                  className={`w-4 h-4 border-2 rounded flex items-center justify-center ${
                                    isSelected
                                      ? 'bg-orange-500 border-orange-500'
                                      : 'border-gray-500'
                                  }`}
                                >
                                  {isSelected && (
                                    <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                                    </svg>
                                  )}
                                </div>
                              </button>

                              {/* Annotation Icon */}
                              <div className="text-gray-400">
                                {getAnnotationIcon(ann.type)}
                              </div>

                              {/* Annotation Number */}
                              <button
                                onClick={() => onSelectAnnotation(ann.id)}
                                className="flex-1 text-left text-sm text-gray-300 hover:text-white transition-colors flex items-center gap-1"
                                title="Select and focus this annotation"
                              >
                                {ann.isAutoGenerated && (
                                  <Sparkles className="w-3 h-3 text-purple-400" />
                                )}
                                <span>#{index + 1}</span>
                                {ann.confidence !== undefined && (
                                  <span className={`ml-1 text-xs font-medium ${getConfidenceColor(ann.confidence)}`}>
                                    {Math.round(ann.confidence * 100)}%
                                  </span>
                                )}
                              </button>

                              {/* Visibility Toggle */}
                              <button
                                onClick={() => onToggleAnnotationVisibility(ann.id)}
                                className="p-1 hover:bg-gray-600 rounded transition-colors text-gray-400 hover:text-white"
                                title={isVisible ? 'Hide annotation on canvas' : 'Show annotation on canvas'}
                              >
                                {isVisible ? (
                                  <Eye className="w-4 h-4" />
                                ) : (
                                  <EyeOff className="w-4 h-4" />
                                )}
                              </button>

                              {/* Delete Button */}
                              <button
                                onClick={() => onDeleteAnnotation(ann.id)}
                                className="p-1 hover:bg-red-600 rounded transition-colors text-gray-400 hover:text-white"
                                title="Delete annotation (Del)"
                              >
                                <Trash2 className="w-4 h-4" />
                              </button>
                            </div>
                          )
                        })
                      )}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        )}
      </div>

      {/* Delete All Confirmation Modal */}
      <Modal
        isOpen={showDeleteAllConfirm}
        onClose={() => setShowDeleteAllConfirm(false)}
        title="Delete All Annotations"
        maxWidth="md"
      >
        <div className="space-y-4">
          <p className="text-gray-300">
            Are you sure you want to delete all {annotations.length} annotations for this image?
          </p>
          <p className="text-red-400 text-sm">This action cannot be undone.</p>
          <div className="flex justify-end gap-3">
            <button
              onClick={() => setShowDeleteAllConfirm(false)}
              className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleDeleteAll}
              className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded transition-colors"
            >
              Delete All
            </button>
          </div>
        </div>
      </Modal>

      {/* Low Confidence Threshold Modal */}
      <Modal
        isOpen={showThresholdModal}
        onClose={() => setShowThresholdModal(false)}
        title="Remove Low Confidence Annotations"
        maxWidth="md"
      >
        <div className="space-y-4">
          <p className="text-gray-300">
            Remove auto-generated annotations with confidence below the threshold.
          </p>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium text-gray-300">
                Confidence Threshold
              </label>
              <span className="text-orange-500 font-medium">
                {Math.round(confidenceThreshold * 100)}%
              </span>
            </div>
            <input
              type="range"
              min="0"
              max="1"
              step="0.05"
              value={confidenceThreshold}
              onChange={(e) => setConfidenceThreshold(parseFloat(e.target.value))}
              className="w-full"
            />
            <div className="flex justify-between text-xs text-gray-500">
              <span>0%</span>
              <span>50%</span>
              <span>100%</span>
            </div>
          </div>

          <div className="bg-gray-700 rounded p-3">
            <p className="text-sm text-gray-300">
              <span className="font-medium text-red-400">{lowConfidenceCount}</span> annotations
              will be removed (below {Math.round(confidenceThreshold * 100)}%)
            </p>
          </div>

          <div className="flex justify-end gap-3">
            <button
              onClick={() => setShowThresholdModal(false)}
              className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleRemoveLowConfidence}
              disabled={lowConfidenceCount === 0}
              className="px-4 py-2 bg-red-600 hover:bg-red-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white rounded transition-colors"
            >
              Remove {lowConfidenceCount}
            </button>
          </div>
        </div>
      </Modal>
    </div>
  )
}
