// Tool types
export type Tool = 'select' | 'rectangle' | 'polygon' | 'point'

// Annotation types
export type AnnotationType = 'rectangle' | 'polygon' | 'point'

// Prompt mode types
export type PromptMode = 'single' | 'auto-apply' | 'batch'

// Label group definition
export interface LabelGroup {
  id: string
  name: string
  isExpanded?: boolean // UI state: expanded/collapsed
  isVisible?: boolean // Group-level visibility toggle (affects all child labels)
  sortOrder?: number // Custom ordering
  createdAt: number
}

// Label definition
export interface Label {
  id: string
  name: string
  color: string
  createdAt: number
  // Group and visibility fields (optional for backward compatibility)
  groupId?: string // Parent group ID (null/undefined = ungrouped)
  isVisible?: boolean // Individual label visibility toggle (default: true)
  sortOrder?: number // Custom ordering within group
}

// Base annotation interface
export interface BaseAnnotation {
  id: string
  imageId: string
  labelId: string
  type: AnnotationType
  createdAt: number
  updatedAt: number
  confidence?: number // Prediction confidence score (0-1) for auto-generated annotations
  isAutoGenerated?: boolean // Flag to distinguish auto-generated from manual annotations
  isVisible?: boolean // Individual annotation visibility toggle (default: true)
}

// Rectangle annotation
export interface RectangleAnnotation extends BaseAnnotation {
  type: 'rectangle'
  x: number
  y: number
  width: number
  height: number
}

// Polygon annotation
export interface PolygonAnnotation extends BaseAnnotation {
  type: 'polygon'
  points: Array<{ x: number; y: number }>
}

// Point annotation
export interface PointAnnotation extends BaseAnnotation {
  type: 'point'
  x: number
  y: number
}

// Union type for all annotations
export type Annotation = RectangleAnnotation | PolygonAnnotation | PointAnnotation

// Image metadata
export interface ImageData {
  id: string
  name: string
  relativePath?: string
  displayName: string
  width: number
  height: number
  blob: Blob
  createdAt: number
}

// Project (collection of images and annotations)
export interface Project {
  id: string
  name: string
  createdAt: number
  updatedAt: number
}

// Edit mode state
export interface EditMode {
  annotationId: string
  type: AnnotationType
}

// COCO Export types
export interface COCOInfo {
  year: number
  version: string
  description: string
  contributor: string
  url?: string
  date_created: string
}

export interface COCOImage {
  id: number
  file_name: string
  width: number
  height: number
  date_captured?: string
}

export interface COCOCategory {
  id: number
  name: string
  supercategory: string
}

export interface COCOAnnotation {
  id: number
  image_id: number
  category_id: number
  bbox?: [number, number, number, number] // [x, y, width, height]
  segmentation?: number[][] // polygon points
  area?: number
  iscrowd: 0 | 1
}

export interface COCODataset {
  info: COCOInfo
  images: COCOImage[]
  annotations: COCOAnnotation[]
  categories: COCOCategory[]
}

// SAM3 types - re-exported from shared package
export type {
  SAM3Response,
  SAM3BatchResponse,
  InferenceResult,
  BatchInferenceResult,
  MaskPolygon,
  BoundingBox,
  APIResponse
} from '@sam3/shared-types'

// Alias for backward compatibility
export type SAM3Mask = import('@sam3/shared-types').MaskPolygon
